#./gen_feat.sh PreGap
#./gen_feat.sh Week 
#./gen_feat.sh TID 
#./gen_feat.sh FDemand 
#./gen_feat.sh PreArrive 
#./gen_feat.sh PreArriveSelf 
#./gen_feat.sh FPOI 
#./gen_feat.sh FWeatherOHE 
#./gen_feat.sh FineArrive
#./gen_feat.sh FineDemand
#./gen_feat.sh FineGap
#./gen_feat.sh FComFineArrive 
#./gen_feat.sh FComFineDemand
#./gen_feat.sh FComPreGap
#./gen_feat.sh FComPreDemand
#./gen_feat.sh FComPreArrive
#./gen_feat.sh FineArriveSelf 
#./gen_feat.sh FDTGap 
#./gen_feat.sh FDTGapByHoliday
#./gen_feat.sh FDTDemand
#./gen_feat.sh FDTSupply
#./gen_feat.sh PreGapAve 
#./gen_feat.sh FTrafficNow
#./gen_feat.sh FTrafficTotal
#./gen_feat.sh FComTrafficTotal
#./gen_feat.sh FDTTrafficTotal
#./gen_feat.sh FDateDistrict
#./gen_feat.sh FDateDistrictDemand
#./gen_feat.sh FDateTimeGap
#./gen_feat.sh FDateTimeDemand
#./gen_feat.sh FHolidayTimeGap
#./gen_feat.sh FHolidayDistrictGap
#./gen_feat.sh FWeekTimeGap
#./gen_feat.sh FWeekDistrictGap
#./gen_feat.sh FPrefixGap
#./gen_feat.sh FPrefixDemand
#./gen_feat.sh FPrefixSupply
#./gen_feat.sh FPrefixArrive
#./gen_feat.sh FPrefixArriveSelf
#./gen_feat.sh FineLeave
#./gen_feat.sh FineGapStat
#./gen_feat.sh FineGap
#./gen_feat.sh FineTimeGap
./gen_feat.sh FineDriverCount
./gen_feat.sh FinePassengerCount
 
 

